# Generated by Django 5.0 on 2023-12-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_rooms', models.IntegerField()),
                ('num_bedroom', models.IntegerField()),
                ('num_bathrooms', models.IntegerField()),
                ('size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=70)),
                ('region', models.CharField(max_length=70)),
                ('is_active', models.BooleanField(default=True)),
                ('booked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking_cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ListingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(max_length=50)),
            ],
        ),
    ]
