# Generated by Django 5.0 on 2023-12-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0005_listing_image_listingimage_delete_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='image',
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='image',
            field=models.FileField(upload_to='listing_images/'),
        ),
    ]
