# Generated by Django 5.0 on 2023-12-19 19:12

import real_estate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0006_remove_listing_image_alter_listingimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listingimage',
            options={},
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='image',
            field=models.FileField(upload_to=real_estate.models.get_image_filename, verbose_name='Image'),
        ),
    ]
