# Generated by Django 5.0 on 2023-12-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0007_alter_listingimage_options_alter_listingimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='cost',
            field=models.IntegerField(default=500),
            preserve_default=False,
        ),
    ]
